import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/coverage/**",
      "contracts/**",
      "packages/indexer-envio/.envio/**",
      "features/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      "no-console": "off",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
    },
  },
  // indexer-envio: envio-env.d.ts is generated by `envio codegen`; its launcher scripts are plain Node ESM.
  // An object holding only `ignores` is a global ignore in flat config, so the ignore and the globals are two entries.
  { ignores: ["packages/indexer-envio/envio-env.d.ts"] },
  {
    files: ["packages/indexer-envio/scripts/**/*.mjs"],
    languageOptions: {
      globals: {
        process: "readonly",
        Buffer: "readonly",
        fetch: "readonly",
        AbortSignal: "readonly",
        URL: "readonly",
        console: "readonly",
      },
    },
  },
);
