// Journey: composer sentence builder caret behaviour.
import { launch, newPage, go, shot, log } from './lib.mjs'

const browser = await launch()
const page = await newPage(browser)
await go(page, '/compose')
await page.locator('#source-input').fill('kleros/gateway-balancer-bot/pull/47')
await page.getByRole('button', { name: 'Pin this commit' }).waitFor({ timeout: 15000 })
await shot(page, 'j-c-resolved')
await page.getByRole('button', { name: 'Pin this commit' }).click()
await page.waitForTimeout(1200)
await page.getByRole('button', { name: 'Continue to policy' }).first().click()
await page.waitForTimeout(400)
await page.getByRole('radio', { name: /BOT-001/ }).first().click()
await page.getByRole('button', { name: 'Continue to claim' }).first().click()
await page.waitForTimeout(500)
await shot(page, 'j-c-claim')
// violation slot
await page.getByRole('button', { name: /^Violation/ }).click()
const ta = page.locator('#violation')
await ta.waitFor()
await ta.pressSequentially('that principal leaks', { delay: 20 })
// move caret to after "that " (index 5)
await ta.evaluate((el) => el.setSelectionRange(5, 5))
await ta.pressSequentially('reporter ', { delay: 30 })
const v = await ta.inputValue()
const pos = await ta.evaluate((el) => el.selectionStart)
log('violation value:', JSON.stringify(v), 'caret', pos, '(expected 14)')
await shot(page, 'j-c-violation')
await page.keyboard.press('Escape')
await page.waitForTimeout(300)
// title drawer
await page.getByRole('button', { name: /Title and requirement/ }).click()
const title = page.locator('#title')
await title.waitFor()
await title.pressSequentially('Deposits never draw reserves', { delay: 15 })
await title.evaluate((el) => el.setSelectionRange(9, 9))
await title.pressSequentially('principal ', { delay: 30 })
log('title value:', JSON.stringify(await title.inputValue()), 'caret', await title.evaluate((el) => el.selectionStart), '(expected 19)')
await page.keyboard.press('Escape')
// environment drawer
await page.getByRole('button', { name: /Environment and reproduction/ }).first().click()
const rt = page.locator('#runtime')
await rt.waitFor()
await rt.fill('')
await rt.pressSequentially('node 22', { delay: 15 })
await rt.evaluate((el) => el.setSelectionRange(5, 5))
await rt.pressSequentially('v', { delay: 30 })
log('runtime value:', JSON.stringify(await rt.inputValue()), 'caret', await rt.evaluate((el) => el.selectionStart), '(expected 6)')
const kv = page.getByRole('textbox', { name: 'Configuration key 1' })
await kv.fill('')
await kv.pressSequentially('CHAIN', { delay: 15 })
await kv.evaluate((el) => el.setSelectionRange(0, 0))
await kv.pressSequentially('X_', { delay: 30 })
log('config key value:', JSON.stringify(await kv.inputValue()), 'caret', await kv.evaluate((el) => el.selectionStart), '(expected 2)')
await shot(page, 'j-c-env')
log('errors', page.errors)
await browser.close()
