// Journey (d): submit evidence on an open claim, direct and commit-reveal.
import { launch, newPage, go, shot, log } from './lib.mjs'
const mobile = process.argv.includes('--mobile')
const tag = `je${mobile ? '-m' : ''}`
const browser = await launch()
const page = await newPage(browser, { mobile })

await go(page, '/claims/pine-0009/evidence')
await page.getByRole('button', { name: /Connect demo wallet/ }).last().click()
await page.waitForTimeout(600)
// submit empty to see validation
await page.getByRole('button', { name: /^Submit on/ }).click()
await page.waitForTimeout(400)
log('focused after invalid submit:', await page.evaluate(() => document.activeElement?.id || document.activeElement?.tagName))
await shot(page, `${tag}-invalid`, true)
await page.locator('#ev-title').fill('Planner draws principal from the gas reserve after a crash')
await page.locator('#ev-summary').fill('After a **crash** between plan and broadcast, the replanned deposit uses the gas reserve.')
await page.locator('#ev-cmd').fill('pnpm vitest run test/pine-0009.spec.ts')
await page.locator('#ev-act').fill('Reserve drops below RESERVE_GAS_MIN')
await page.getByRole('button', { name: /^Submit on/ }).click()
await page.waitForTimeout(400)
log('focused when only Expected is missing:', await page.evaluate(() => document.activeElement?.id))
await shot(page, `${tag}-missing-expected`)
await page.locator('#ev-exp').fill('Reserve stays at or above RESERVE_GAS_MIN')
for (const cb of await page.getByRole('checkbox').all()) await cb.check()
await page.getByRole('button', { name: /^Submit on/ }).click()
await page.getByRole('heading', { name: 'Evidence submitted' }).waitFor({ timeout: 30000 }).catch(async (e) => { await shot(page, `${tag}-direct-stuck`, true); throw e })
await shot(page, `${tag}-direct-done`, true)
log('direct ok')
await page.getByRole('button', { name: 'Submit something else' }).click()
await page.waitForTimeout(500)
log('form cleared? title =', JSON.stringify(await page.locator('#ev-title').inputValue()))
// commit mode
await page.getByRole('radio', { name: /Commit, reveal later/ }).click().catch(async () => {
  await page.getByRole('button', { name: /Commit, reveal later/ }).click()
})
await page.locator('#ev-title').fill('Commitment for a second path')
await page.locator('#ev-summary').fill('Details kept private until reveal.')
await page.locator('#ev-cmd').fill('pnpm vitest run test/pine-0009b.spec.ts')
await page.locator('#ev-act').fill('Second bridge started')
await page.locator('#ev-exp').fill('One bridge per operation')
for (const cb of await page.getByRole('checkbox').all()) await cb.check()
await shot(page, `${tag}-commit-form`, true)
await page.getByRole('button', { name: /Commit the evidence hash/ }).click()
await page.getByRole('heading', { name: 'Evidence submitted' }).waitFor({ timeout: 30000 })
await shot(page, `${tag}-commit-done`, true)
log('commit ok')
await go(page, '/claims/pine-0009')
await page.getByRole('tab', { name: /^Evidence/ }).click()
await page.waitForTimeout(500)
await shot(page, `${tag}-feed`, true)
log('errors', page.errors)
await browser.close()
