import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { hashJson } from '@pine/core'
import Ajv2020 from 'ajv/dist/2020'
import { beforeAll, describe, expect, it } from 'vitest'
import YAML from 'yaml'
import { buildOpenApi } from '../scripts/openapi-spec'
import { PineDataError, RestDataProvider } from '../src'
import {
  accountFromWire,
  accountToWire,
  activityFromWire,
  activityToWire,
  claimDetailFromWire,
  claimDetailToWire,
  claimSummaryFromWire,
  claimSummaryToWire,
  depthFromWire,
  depthToWire,
  draftFromWire,
  draftToWire,
  evidenceFromWire,
  evidenceToWire,
  pageFromWire,
  policyFromWire,
  policyToWire,
  portfolioFromWire,
  portfolioToWire,
  pricesFromWire,
  pricesToWire,
  statsFromWire,
  statsToWire,
  type WireClaimDetail,
  type WireDepth,
  type WirePriceHistory,
} from '../src/rest/wire'

const here = dirname(fileURLToPath(import.meta.url))
const DOC_PATH = resolve(here, '../../../docs/indexer/rest-api.openapi.yaml')

type Doc = {
  paths: Record<string, Record<string, { operationId: string; responses: Record<string, { content?: Record<string, { schema: unknown; examples?: Record<string, { value: unknown }> }> }>; requestBody?: { content: Record<string, { schema: unknown; examples?: Record<string, { value: unknown }> }> } }>>
  components: { schemas: Record<string, unknown> }
}

let doc: Doc

beforeAll(async () => {
  if (process.env.PINE_WRITE_OPENAPI === '1' || !existsSync(DOC_PATH)) {
    const header =
      '# Pine REST indexer API — OpenAPI 3.1 contract (generated by packages/data/scripts/openapi-spec.ts).\n' +
      '# Regenerate: pnpm --filter @pine/data openapi. Do not hand-edit examples; edit the generator.\n'
    writeFileSync(DOC_PATH, header + YAML.stringify(await buildOpenApi(), { lineWidth: 0, aliasDuplicateObjects: false }))
  }
  doc = YAML.parse(readFileSync(DOC_PATH, 'utf8')) as Doc
})

function operations() {
  const out: { path: string; method: string; operationId: string; status: string; schema: unknown; examples: Record<string, { value: unknown }> }[] = []
  for (const [path, methods] of Object.entries(doc.paths)) {
    for (const [method, op] of Object.entries(methods)) {
      for (const [status, res] of Object.entries(op.responses)) {
        const c = res.content?.['application/json']
        if (c) out.push({ path, method, operationId: op.operationId, status, schema: c.schema, examples: c.examples ?? {} })
      }
      const body = op.requestBody?.content['application/json']
      if (body) out.push({ path, method, operationId: `${op.operationId}:request`, status: 'request', schema: body.schema, examples: body.examples ?? {} })
    }
  }
  return out
}

describe('OpenAPI contract (docs/indexer/rest-api.openapi.yaml)', () => {
  it('is OpenAPI 3.1 and covers every endpoint the frontend calls', () => {
    const d = doc as unknown as { openapi: string; paths: Record<string, unknown> }
    expect(d.openapi).toBe('3.1.0')
    for (const p of [
      '/claims',
      '/claims/{id}',
      '/markets/{chain_id}/{address}/claim',
      '/claims/{id}/prices',
      '/claims/{id}/depth',
      '/claims/{id}/evidence',
      '/activity',
      '/portfolio/{address}',
      '/policies',
      '/policies/{id}',
      '/stats',
      '/drafts',
      '/drafts/{id}',
      '/accounts/{login}',
      '/accounts/{login}/wallets',
      '/accounts/{login}/wallets/{address}',
      '/accounts/{login}/wallets/{address}/primary',
      '/accounts/{login}/preferences',
      '/accounts/{login}/export',
    ]) {
      expect(d.paths, p).toHaveProperty([p])
    }
  })

  it('has at least one example for every JSON response and request body', () => {
    for (const op of operations()) {
      expect(Object.keys(op.examples).length, `${op.operationId} ${op.status}`).toBeGreaterThan(0)
    }
  })

  it('every example validates against its schema', () => {
    const ajv = new Ajv2020({ strict: false, validateFormats: false, allErrors: true })
    ajv.addSchema({ $id: 'pine-openapi', components: { schemas: doc.components.schemas } } as Record<string, unknown>)
    for (const op of operations()) {
      const schema = JSON.parse(JSON.stringify(op.schema).replaceAll('"#/components/', '"pine-openapi#/components/'))
      const validate = ajv.compile(schema)
      for (const [name, ex] of Object.entries(op.examples)) {
        const ok = validate(resolveExample(ex as { value?: unknown; $ref?: string }))
        expect(ok, `${op.operationId} ${op.status} example "${name}": ${ajv.errorsText(validate.errors)}`).toBe(true)
      }
    }
  })
})

function resolveExample(ex: { value?: unknown; $ref?: string }): unknown {
  if (ex.$ref) {
    const name = ex.$ref.replace('#/components/examples/', '')
    const target = (doc.components as unknown as { examples: Record<string, { value: unknown }> }).examples[name]
    if (!target) throw new Error(`dangling example ref ${ex.$ref}`)
    return target.value
  }
  return ex.value
}

function example<T>(path: string, method: string, status: string, name?: string): T {
  const c = doc.paths[path]?.[method]?.responses[status]?.content?.['application/json']
  const ex = (c?.examples ?? {}) as Record<string, { value?: unknown; $ref?: string }>
  const key = name ?? Object.keys(ex)[0]
  if (!key || !ex[key]) throw new Error(`no example ${path} ${method} ${status} ${name ?? ''}`)
  return resolveExample(ex[key]) as T
}

describe('REST wire mappers against the OpenAPI examples', () => {
  it('claim list round-trips', () => {
    const w = example<{ items: Parameters<typeof claimSummaryFromWire>[0][]; next_cursor: string; total: number }>('/claims', 'get', '200')
    const page = pageFromWire(w, claimSummaryFromWire)
    expect(page.items.length).toBe(w.items.length)
    expect(page.nextCursor).toBe(w.next_cursor)
    expect(page.items.map(claimSummaryToWire)).toEqual(w.items)
    for (const c of page.items) {
      expect(c.source.commitSha).toMatch(/^[0-9a-f]{40}$/)
      expect(c.status).toBe('open')
    }
  })

  it.each(['flagship', 'arbitration', 'publishing'])('claim detail "%s" round-trips and keeps the manifest hash', (name) => {
    const w = example<WireClaimDetail>('/claims/{id}', 'get', '200', name)
    const d = claimDetailFromWire(w)
    expect(claimDetailToWire(d)).toEqual(w)
    expect(hashJson(d.manifest)).toBe(d.manifestHash)
    expect(d.manifest.question.text).toContain(d.source.commitSha)
    if (name === 'arbitration') {
      expect(d.oracle?.arbitration.requested).toBe(true)
      expect(d.oracle?.arbitration.klerosUrl).toContain('resolve.kleros.io')
      expect(d.oracle?.history.map((h) => Number(h.bond))).toEqual([10, 20, 40])
    }
    if (name === 'publishing') {
      expect(d.publication?.resumable).toBe(true)
      expect(d.publication?.steps.find((s) => s.id === 'split_position')?.error).toMatch(/User rejected/)
      expect(d.yesPrice).toBeUndefined()
    }
  })

  it('prices, depth, evidence, activity, portfolio, policies, stats round-trip', () => {
    const p = example<WirePriceHistory>('/claims/{id}/prices', 'get', '200')
    expect(pricesToWire(p.claim_id, p.range, pricesFromWire(p))).toEqual(p)

    const dw = example<WireDepth>('/claims/{id}/depth', 'get', '200')
    const depth = depthFromWire(dw)
    expect(depth.levels.filter((l) => l.side === 'bid').every((l) => l.price < depth.mid)).toBe(true)
    expect(depthToWire(dw.claim_id, depth)).toEqual(dw)

    const ev = example<{ items: Parameters<typeof evidenceFromWire>[0][] }>('/claims/{id}/evidence', 'get', '200')
    expect(ev.items.map(evidenceFromWire).map(evidenceToWire)).toEqual(ev.items)

    const act = example<{ items: Parameters<typeof activityFromWire>[0][] }>('/activity', 'get', '200')
    expect(act.items.map(activityFromWire).map(activityToWire)).toEqual(act.items)

    const pf = example<Parameters<typeof portfolioFromWire>[0]>('/portfolio/{address}', 'get', '200')
    const portfolio = portfolioFromWire(pf)
    expect(portfolio.positions.some((x) => x.redeemable)).toBe(true)
    expect(portfolio.liquidity.some((x) => !x.inRange)).toBe(true)
    expect(portfolioToWire(portfolio)).toEqual(pf)

    const pol = example<{ items: Parameters<typeof policyFromWire>[0][] }>('/policies', 'get', '200')
    const policies = pol.items.map(policyFromWire)
    expect(policies.find((x) => x.id === 'SC-001')?.status).toBe('gated')
    expect(policies.map(policyToWire)).toEqual(pol.items)

    const st = example<Parameters<typeof statsFromWire>[0]>('/stats', 'get', '200')
    expect(statsToWire(statsFromWire(st))).toEqual(st)
  })

  it('drafts and accounts round-trip', () => {
    const dl = example<{ items: Parameters<typeof draftFromWire>[0][] }>('/drafts', 'get', '200')
    expect(dl.items.map(draftFromWire).map(draftToWire)).toEqual(dl.items)
    const acc = example<Parameters<typeof accountFromWire>[0]>('/accounts/{login}', 'get', '200')
    const account = accountFromWire(acc)
    expect(account.wallets.filter((w) => w.primary)).toHaveLength(1)
    expect(accountToWire(account)).toEqual(acc)
  })
})

/** A fetch stub that serves the OpenAPI examples like a REST indexer would. */
function stubServer(base: string) {
  const calls: string[] = []
  const fetcher = (async (input: RequestInfo | URL) => {
    const url = new URL(String(input))
    calls.push(url.pathname + url.search)
    const path = url.pathname.slice(new URL(base).pathname.length)
    const json = (status: number, body: unknown) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } })
    if (path === '/claims') return json(200, example('/claims', 'get', '200'))
    if (path === '/claims/pine-0009') return json(200, example('/claims/{id}', 'get', '200', 'flagship'))
    if (path === '/claims/pine-0009/prices') return json(200, example('/claims/{id}/prices', 'get', '200'))
    if (path === '/claims/pine-0009/depth') return json(200, example('/claims/{id}/depth', 'get', '200'))
    if (path === '/claims/pine-0009/evidence') return json(200, example('/claims/{id}/evidence', 'get', '200'))
    if (path.startsWith('/markets/100/')) return json(200, example('/markets/{chain_id}/{address}/claim', 'get', '200'))
    if (path === '/activity') return json(200, example('/activity', 'get', '200'))
    if (path.startsWith('/portfolio/')) return json(200, example('/portfolio/{address}', 'get', '200'))
    if (path === '/policies') return json(200, example('/policies', 'get', '200'))
    if (path === '/policies/BOT-001') return json(200, example('/policies/{id}', 'get', '200'))
    if (path === '/stats') return json(200, example('/stats', 'get', '200'))
    if (path === '/claims/rate-limited') return json(429, { error: { code: 'rate_limited', message: 'slow down' } })
    if (path === '/claims/boom') return new Response('upstream exploded', { status: 502 })
    return json(404, { error: { code: 'not_found', message: 'nope' } })
  }) as typeof fetch
  return { fetcher, calls }
}

describe('RestDataProvider', () => {
  const base = 'https://api.pine.test/v1'

  it('serializes ClaimQuery to the contract’s query parameters', async () => {
    const { fetcher, calls } = stubServer(base)
    const p = new RestDataProvider({ baseUrl: `${base}/`, fetch: fetcher })
    const page = await p.listClaims({ status: ['open', 'disputed'], policyId: 'BOT-001', family: 'BOT', repo: 'kleros/gateway-balancer-bot', chainId: 100, search: ' keeper ', sort: 'deadline', cursor: '20', limit: 5 })
    expect(page.items.length).toBeGreaterThan(0)
    const url = new URL(`https://x${calls[0]}`)
    expect(url.pathname).toBe('/v1/claims')
    expect(url.searchParams.getAll('status')).toEqual(['open', 'disputed'])
    expect(url.searchParams.get('policy_id')).toBe('BOT-001')
    expect(url.searchParams.get('chain_id')).toBe('100')
    expect(url.searchParams.get('search')).toBe('keeper')
    expect(url.searchParams.get('sort')).toBe('deadline')
    expect(url.searchParams.get('cursor')).toBe('20')
    expect(url.searchParams.get('limit')).toBe('5')
  })

  it('reads every endpoint and maps to domain types', async () => {
    const { fetcher, calls } = stubServer(base)
    const p = new RestDataProvider({ baseUrl: base, fetch: fetcher })
    const claim = await p.getClaim('pine-0009')
    expect(claim?.policy.id).toBe('BOT-001')
    expect(claim && hashJson(claim.manifest)).toBe(claim?.manifestHash)
    expect(await p.getClaimByMarket(100, claim!.marketAddress!)).not.toBeNull()
    expect(calls.at(-1)).toContain(claim!.marketAddress!.toLowerCase())
    expect((await p.getPriceHistory('pine-0009', '24h')).length).toBeGreaterThan(0)
    expect(calls.at(-1)).toContain('range=24h')
    expect((await p.getDepth('pine-0009', 'yes'))?.levels.length).toBeGreaterThan(0)
    expect((await p.listEvidence('pine-0009')).length).toBeGreaterThan(0)
    expect((await p.listActivity({ claimId: 'pine-0005', types: ['trade', 'answer_posted'] })).items.length).toBeGreaterThan(0)
    expect(calls.at(-1)).toContain('types=trade&types=answer_posted')
    expect((await p.getPortfolio('0xDE30BD7C2A0B6f1e5C4b1a9F2f5d3C8E7a6b0D30')).positions.length).toBeGreaterThan(0)
    expect((await p.listPolicies()).length).toBe(3)
    expect((await p.getPolicy('BOT-001'))?.id).toBe('BOT-001')
    expect((await p.getStats()).collateralSymbol).toBe('sDAI')
  })

  it('accepts a relative base URL (app-proxied API)', async () => {
    const seen: string[] = []
    const fetcher = (async (url: RequestInfo | URL) => {
      seen.push(String(url))
      return new Response(JSON.stringify({ items: [] }))
    }) as typeof fetch
    await new RestDataProvider({ baseUrl: '/api/pine/', fetch: fetcher }).listClaims({ status: 'open', limit: 3 })
    expect(seen[0]).toBe('/api/pine/claims?status=open&limit=3')
  })

  it('maps 404 to null and errors to PineDataError codes', async () => {
    const { fetcher } = stubServer(base)
    const p = new RestDataProvider({ baseUrl: base, fetch: fetcher })
    expect(await p.getClaim('pine-9999')).toBeNull()
    expect(await p.getDepth('pine-9999', 'yes')).toBeNull()
    await expect(p.getClaim('rate-limited')).rejects.toMatchObject({ code: 'rate_limited', message: 'slow down' })
    await expect(p.getClaim('boom')).rejects.toMatchObject({ code: 'network' })
    const failing = new RestDataProvider({ baseUrl: base, fetch: (async () => { throw new TypeError('fetch failed') }) as typeof fetch })
    const err = await failing.listClaims().catch((e: unknown) => e)
    expect(err).toBeInstanceOf(PineDataError)
    expect((err as PineDataError).code).toBe('network')
  })
})
