#!/usr/bin/env bash
# Pine local integration stack. DEVELOPMENT ONLY: boots the whole backend on this machine against a LOCAL anvil fork of
# Gnosis Chain, for a frontend on http://localhost:3004 and its Playwright tests.
#
#   Postgres 16 (Docker, 127.0.0.1:55432) -> roles + database (deploy/postgres) -> anvil fork (chain id 100, :8545,
#   1 s blocks, finalized = head - 2) -> Pine contracts deployed with anvil dev account #0 -> API + indexer migrations ->
#   native indexer (:9465 health) -> API dev server (packages/api/scripts/dev-server.ts: API :3000, user content :3001,
#   metrics :9464, dev control :3999; fake GitHub + fake IPFS, RPC = the fork).
#
# Idempotent: healthy parts are kept, missing or dead parts are (re)started. A new chain always gets a new deployment and
# a fresh database (the old index would not match the new chain). Nothing is broadcast to a real network: the fork only
# READS Gnosis state from a public archive RPC; transactions exist only inside the local anvil.
#
# Usage: scripts/dev-stack/up.sh [--restart]   --restart: restart the indexer and the API even when they are healthy.
# State, logs and generated dev-only secrets: scripts/dev-stack/.state/ (git-ignored). Stop: scripts/dev-stack/down.sh
set -euo pipefail

# shellcheck source=config.sh
source "$(dirname "${BASH_SOURCE[0]}")/config.sh"

RESTART=0
for arg in "$@"; do
  case $arg in
    --restart) RESTART=1 ;;
    -h | --help)
      sed -n '2,17p' "$0"
      exit 0
      ;;
    *) die "unknown argument: $arg" ;;
  esac
done

# ---------------------------------------------------------------------------------------------------------- preflight
for tool in docker anvil forge node jq openssl curl nc; do
  command -v "$tool" >/dev/null 2>&1 || die "$tool is required on PATH"
done
docker info >/dev/null 2>&1 || die "Docker is not running"
NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]')
[ "$NODE_MAJOR" -ge 22 ] || die "Node 22 or newer is required (the repository targets Node 24)"
[ -d "$REPO_ROOT/packages/api/node_modules/tsx" ] || die "dependencies are missing: run 'pnpm install --frozen-lockfile' at the repository root"

mkdir -p "$LOG_DIR" "$PID_DIR"
chmod 700 "$STATE_DIR"

# ------------------------------------------------------------------------------------------- dev-only secrets (once)
SECRETS=$STATE_DIR/secrets.env
if [ ! -f "$SECRETS" ]; then
  (
    umask 077
    {
      echo "# Generated by scripts/dev-stack/up.sh: random DEV-ONLY credentials of the local stack (never used elsewhere)."
      echo "PG_SUPERUSER_PASSWORD=$(openssl rand -hex 24)"
      echo "PG_MIGRATOR_PASSWORD=$(openssl rand -hex 24)"
      echo "PG_API_PASSWORD=$(openssl rand -hex 24)"
      echo "PG_INDEXER_PASSWORD=$(openssl rand -hex 24)"
      echo "PG_READONLY_PASSWORD=$(openssl rand -hex 24)"
      echo "GITHUB_CLIENT_SECRET=$(openssl rand -hex 24)"
      echo "TOKEN_KEY=$(openssl rand -base64 32)"
      echo "PINNING_TOKEN=$(openssl rand -hex 24)"
    } >"$SECRETS"
  )
  log "generated dev-only secrets in $SECRETS"
fi
# shellcheck disable=SC1090
source "$SECRETS"

# ----------------------------------------------------------------------------------------------------------- postgres
pg_state=$(docker inspect -f '{{.State.Running}}' "$PG_CONTAINER" 2>/dev/null || echo missing)
case $pg_state in
  true) log "postgres: container $PG_CONTAINER running" ;;
  false)
    log "postgres: starting the existing container $PG_CONTAINER"
    docker start "$PG_CONTAINER" >/dev/null
    ;;
  *)
    port_busy "$PG_PORT" && die "port $PG_PORT is in use by another process"
    log "postgres: creating container $PG_CONTAINER ($PG_IMAGE) on 127.0.0.1:$PG_PORT"
    docker run -d --name "$PG_CONTAINER" --label pine.dev-stack=1 -p "127.0.0.1:$PG_PORT:5432" \
      -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD="$PG_SUPERUSER_PASSWORD" "$PG_IMAGE" >/dev/null
    ;;
esac
for _ in $(seq 1 60); do
  # TCP inside the container: the image's init-time server listens on the socket only, so this waits for the real one.
  docker exec "$PG_CONTAINER" pg_isready -U postgres -h 127.0.0.1 -q >/dev/null 2>&1 && break
  sleep 1
done
docker exec "$PG_CONTAINER" pg_isready -U postgres -h 127.0.0.1 -q >/dev/null 2>&1 || die "postgres did not become ready (docker logs $PG_CONTAINER)"
docker exec "$PG_CONTAINER" postgres --version | grep -q ' 16\.' || die "$PG_CONTAINER is not PostgreSQL 16"

psql_admin() { docker exec -i "$PG_CONTAINER" psql -U postgres -v ON_ERROR_STOP=1 -q "$@"; }
psql_admin <"$REPO_ROOT/deploy/postgres/00-roles.sql"
psql_admin <<SQL
ALTER ROLE pine_migrator PASSWORD '$PG_MIGRATOR_PASSWORD';
ALTER ROLE pine_api PASSWORD '$PG_API_PASSWORD';
ALTER ROLE pine_indexer PASSWORD '$PG_INDEXER_PASSWORD';
ALTER ROLE pine_readonly PASSWORD '$PG_READONLY_PASSWORD';
SQL

create_database() {
  psql_admin -v pine_db="$PG_DB" <"$REPO_ROOT/deploy/postgres/01-database.sql"
  log "postgres: database $PG_DB created"
}
db_exists() { [ "$(docker exec "$PG_CONTAINER" psql -U postgres -Atc "SELECT 1 FROM pg_database WHERE datname = '$PG_DB'")" = "1" ]; }
DB_CREATED=0
if ! db_exists; then
  create_database
  DB_CREATED=1
fi

# -------------------------------------------------------------------------------------------------------------- anvil
anvil_ok() {
  local version chain
  version=$(rpc_call web3_clientVersion | jq -r '.result // empty' 2>/dev/null || true)
  chain=$(rpc_call eth_chainId | jq -r '.result // empty' 2>/dev/null || true)
  case $version in anvil/*) [ "$chain" = "0x64" ] ;; *) return 1 ;; esac
}

CHAIN_FRESH=0
if service_pid anvil >/dev/null && anvil_ok; then
  log "anvil: running (fork of Gnosis, chain id 100) on $RPC_PRIMARY"
else
  stop_service anvil
  port_busy "$ANVIL_PORT" && die "port $ANVIL_PORT is in use by a process up.sh did not start"
  FORK_URL=""
  for candidate in $FORK_URLS; do
    answer=$(curl -s -m 15 -X POST -H 'content-type: application/json' --data '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}' "$candidate" | jq -r '.result // empty' 2>/dev/null || true)
    if [ "$answer" = "0x64" ]; then
      FORK_URL=$candidate
      break
    fi
  done
  [ -n "$FORK_URL" ] || die "no Gnosis RPC reachable to fork from (tried: $FORK_URLS)"
  log "anvil: forking Gnosis at block $FORK_BLOCK from $FORK_URL"
  node "$DEV_STACK_DIR/spawn-detached.mjs" "$STATE_DIR" "$LOG_DIR/anvil.log" "$PID_DIR/anvil.pid" -- \
    anvil --host 127.0.0.1 --port "$ANVIL_PORT" --chain-id 100 \
    --fork-url "$FORK_URL" --fork-block-number "$FORK_BLOCK" --retries 10 --fork-retry-backoff 1000 --timeout 45000 \
    --block-time 1 --slots-in-an-epoch 1 --balance 100000 --prune-history 512
  for _ in $(seq 1 120); do
    anvil_ok && break
    service_pid anvil >/dev/null || die "anvil exited (see $LOG_DIR/anvil.log)"
    sleep 0.5
  done
  anvil_ok || die "anvil did not become ready (see $LOG_DIR/anvil.log)"
  CHAIN_FRESH=1
fi

# A fork's new blocks continue from the fork block's timestamp (behind the wall clock by the fork block's age), which
# the API reports as a stale read model. Move the chain clock forward to now once; interval mining then follows the
# wall clock. Chain time can only move forward, so a chain that is ahead is left alone.
chain_ts=$(rpc_call eth_getBlockByNumber '["latest",false]' | jq -r '.result.timestamp' | xargs printf '%d')
now_ts=$(date +%s)
if [ $((now_ts - chain_ts)) -gt 30 ]; then
  rpc_call evm_setNextBlockTimestamp "[$now_ts]" >/dev/null
  rpc_call evm_mine >/dev/null
  log "anvil: chain clock moved forward by $((now_ts - chain_ts))s to the wall clock"
fi

# ---------------------------------------------------------------------------------------------------------- contracts
DEPLOYMENT=$STATE_DIR/deployment.json
NEED_DEPLOY=1
if [ "$CHAIN_FRESH" = 0 ] && [ -f "$DEPLOYMENT" ]; then
  claim=$(jq -r '.claimRegistry' "$DEPLOYMENT")
  code=$(rpc_call eth_getCode "[\"$claim\",\"latest\"]" | jq -r '.result // "0x"')
  [ "${#code}" -gt 2 ] && NEED_DEPLOY=0
fi
RESET_DB=0
if [ "$NEED_DEPLOY" = 1 ]; then
  log "contracts: deploying EvidenceRegistry + ClaimRegistry with anvil account #0 ($DEPLOYER)"
  (
    cd "$REPO_ROOT/contracts"
    PINE_DEPLOYER=$DEPLOYER forge script script/Deploy.s.sol --rpc-url "$RPC_PRIMARY" --broadcast --unlocked --sender "$DEPLOYER" --json
  ) >"$LOG_DIR/deploy.jsonl" 2>"$LOG_DIR/deploy.log" || die "forge deployment failed (see $LOG_DIR/deploy.log)"
  record=$(grep '^{' "$LOG_DIR/deploy.jsonl" | jq -c 'select(.logs != null) | .logs[]' | jq -r 'select(test("claimRegistry"))' | head -n 1)
  [ -n "$record" ] || die "no deployment record in the forge output ($LOG_DIR/deploy.jsonl)"
  block=$(grep '^{' "$LOG_DIR/deploy.jsonl" | jq -r 'select(.contract_address != null and .status == "success") | .block_number' | sort -n | head -n 1)
  [[ "$block" =~ ^[0-9]+$ ]] || die "no deployment receipt block in the forge output"
  echo "$record" | jq --argjson block "$block" --arg fork "$FORK_BLOCK" \
    '{claimRegistry, evidenceRegistry, deploymentBlock: $block, deployer, chainId, forkBlock: ($fork | tonumber), record: .}' >"$DEPLOYMENT"
  for key in claimRegistry evidenceRegistry; do
    address=$(jq -r ".$key" "$DEPLOYMENT")
    [[ "$address" =~ ^0x[0-9a-fA-F]{40}$ ]] || die "invalid $key in the deployment record"
    code=$(rpc_call eth_getCode "[\"$address\",\"latest\"]" | jq -r '.result // "0x"')
    [ "${#code}" -gt 2 ] || die "$key $address has no code on the fork"
  done
  RESET_DB=1
fi
CLAIM_REGISTRY=$(jq -r '.claimRegistry' "$DEPLOYMENT")
EVIDENCE_REGISTRY=$(jq -r '.evidenceRegistry' "$DEPLOYMENT")
DEPLOYMENT_BLOCK=$(jq -r '.deploymentBlock' "$DEPLOYMENT")
log "contracts: ClaimRegistry $CLAIM_REGISTRY, EvidenceRegistry $EVIDENCE_REGISTRY, deployment block $DEPLOYMENT_BLOCK"

# ---------------------------------------------------------------------------------------------- database + migrations
# A database created in this run (new container, or one removed by hand) means running services hold dead connections.
[ "$DB_CREATED" = 1 ] && RESTART=1
if [ "$RESET_DB" = 1 ] && [ "$DB_CREATED" = 0 ]; then
  stop_service api
  stop_service indexer
  psql_admin -c "DROP DATABASE IF EXISTS $PG_DB WITH (FORCE)"
  log "postgres: database $PG_DB dropped (new chain deployment)"
  create_database
fi

PG_URL_BASE="127.0.0.1:$PG_PORT/$PG_DB"
MIGRATOR_URL="postgres://pine_migrator:$PG_MIGRATOR_PASSWORD@$PG_URL_BASE"
# Run with node directly (not pnpm): pnpm rewrites pnpm-lock.yaml's packageManagerDependencies, which is frozen.
(cd "$REPO_ROOT/packages/api" && PINE_MIGRATOR_DATABASE_URL=$MIGRATOR_URL node --import tsx src/migrate.ts) >"$LOG_DIR/migrate-api.log" 2>&1 ||
  die "API migrations failed (see $LOG_DIR/migrate-api.log)"
(cd "$REPO_ROOT/packages/indexer-native" && MIGRATION_DATABASE_URL=$MIGRATOR_URL node --import tsx src/migrate-cli.ts) >"$LOG_DIR/migrate-indexer.log" 2>&1 ||
  die "indexer migrations failed (see $LOG_DIR/migrate-indexer.log)"
log "migrations: API and indexer up to date"

# -------------------------------------------------------------------------------------------------------- env files
TERMS_DIGEST=0x$(printf '%s' "Pine local development terms (dev-stack). Not legal terms." | openssl dgst -sha256 -r | cut -d' ' -f1)

write_env() {
  # $1 = target file; content on stdin. Prints "changed" when the content differs from the current file.
  local target=$1 tmp
  tmp=$(mktemp "$STATE_DIR/.env.XXXXXX")
  cat >"$tmp"
  chmod 600 "$tmp"
  if [ -f "$target" ] && cmp -s "$tmp" "$target"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$target"
    echo changed
  fi
}

INDEXER_ENV_CHANGED=$(write_env "$STATE_DIR/indexer.env" <<EOF
# Generated by scripts/dev-stack/up.sh (dev only). @pine/indexer-native configuration, see its README.
PINE_INDEXER_ENV=development
RPC_ALLOW_INSECURE_HTTP=true
DATABASE_URL=postgres://pine_indexer:$PG_INDEXER_PASSWORD@$PG_URL_BASE
RPC_PRIMARY_URL=$RPC_PRIMARY
RPC_SECONDARY_URL=$RPC_SECONDARY
CHAIN_ID=100
CLAIM_REGISTRY_ADDRESS=$CLAIM_REGISTRY
EVIDENCE_REGISTRY_ADDRESS=$EVIDENCE_REGISTRY
DEPLOYMENT_BLOCK=$DEPLOYMENT_BLOCK
POLL_INTERVAL_MS=1000
CHUNK_SIZE=500
METRICS_HOST=127.0.0.1
METRICS_PORT=$INDEXER_METRICS_PORT
LOG_LEVEL=info
EOF
)

API_ENV_CHANGED=$(write_env "$STATE_DIR/api.env" <<EOF
# Generated by scripts/dev-stack/up.sh (dev only). Variables: packages/api/.env.example. Read by scripts/dev-server.ts,
# which refuses anything that is not development + loopback, and sets the fake IPFS targets itself.
PINE_ENVIRONMENT=development
PINE_PUBLIC_ORIGIN=$PUBLIC_ORIGIN
PINE_USER_CONTENT_ORIGIN=$USER_CONTENT_ORIGIN
PINE_CHAIN_ID=100
PINE_HOST=127.0.0.1
PINE_PORT=$API_PORT
PINE_USER_CONTENT_HOST=127.0.0.1
PINE_USER_CONTENT_PORT=$USER_CONTENT_PORT
PINE_METRICS_HOST=127.0.0.1
PINE_METRICS_PORT=$API_METRICS_PORT
PINE_TRUST_PROXY_HOPS=0
PINE_LOG_LEVEL=info
PINE_DATABASE_POOL_MAX=10
PINE_CLAIM_REGISTRY=$CLAIM_REGISTRY
PINE_EVIDENCE_REGISTRY=$EVIDENCE_REGISTRY
PINE_DEPLOYMENT_BLOCK=$DEPLOYMENT_BLOCK
PINE_ENABLED_POLICY_FAMILIES=FUNC-001,BOT-001
# Every catalog version is still a draft; development may publish drafts (production refuses this).
PINE_ALLOW_DRAFT_POLICIES=true
PINE_INDEXER_BACKEND=native
PINE_MAX_INDEXER_LAG_SECONDS=900
PINE_TERMS_DIGEST=$TERMS_DIGEST
# anvil dev account #9 is an admin (moderation routes); every other wallet is a regular user.
PINE_ADMIN_WALLETS=0xa0ee7a142d267c1f36714e4a8f75612f20a79720
# Generous abuse limits: Playwright drives many requests from one loopback IP.
PINE_IP_FLOOD_LIMIT_PER_MINUTE=100000
PINE_USER_RATE_LIMIT_PER_MINUTE=100000
PINE_QUOTA_CLAIM_DRAFTS_PER_DAY=10000
PINE_QUOTA_PUBLICATIONS_PER_DAY=10000
PINE_QUOTA_PLANS_PER_DAY=100000
PINE_QUOTA_EVIDENCE_UPLOADS_PER_DAY=10000
PINE_QUOTA_EVIDENCE_BYTES_PER_DAY=1073741824
PINE_QUOTA_GITHUB_CALLS_PER_HOUR=100000
PINE_DATABASE_URL=postgres://pine_api:$PG_API_PASSWORD@$PG_URL_BASE
PINE_READ_MODEL_DATABASE_URL=postgres://pine_readonly:$PG_READONLY_PASSWORD@$PG_URL_BASE
PINE_RPC_URL_PRIMARY=$RPC_PRIMARY
PINE_RPC_URL_SECONDARY=$RPC_SECONDARY
PINE_GITHUB_KIND=app
PINE_GITHUB_CLIENT_ID=Iv1.pinedevclient0001
PINE_GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
PINE_TOKEN_KEY_CURRENT=dev1:$TOKEN_KEY
PINE_DEV_PINNING_TOKEN=$PINNING_TOKEN
PINE_DEV_CONTROL_PORT=$CONTROL_PORT
EOF
)

write_env "$STATE_DIR/frontend.env" >/dev/null <<EOF
# Generated by scripts/dev-stack/up.sh: the values the Pine frontend needs against the local stack.
NEXT_PUBLIC_PINE_DATA_SOURCE=api
PINE_API_INTERNAL_URL=http://127.0.0.1:$API_PORT
NEXT_PUBLIC_CHAIN_ID=100
NEXT_PUBLIC_PINE_CLAIM_REGISTRY=$CLAIM_REGISTRY
NEXT_PUBLIC_PINE_EVIDENCE_REGISTRY=$EVIDENCE_REGISTRY
NEXT_PUBLIC_PINE_DEPLOYMENT_BLOCK=$DEPLOYMENT_BLOCK
NEXT_PUBLIC_PINE_RPC_URL=$RPC_PRIMARY
NEXT_PUBLIC_RPC_URL_100=$RPC_PRIMARY
NEXT_PUBLIC_SITE_URL=$PUBLIC_ORIGIN
PINE_DEV_CONTROL_URL=http://127.0.0.1:$CONTROL_PORT
# Lets Next.js proxy /api/v1/* etc. to the local API (frontend/apps/prism/next.config.ts; loopback only, never production).
PINE_DEV_PROXY=1
# GitHub is simulated here: "Link GitHub" opens the dev control server's consent page instead of github.com.
NEXT_PUBLIC_PINE_DEV_GITHUB_ORIGIN=http://127.0.0.1:$CONTROL_PORT
# Local fork only: on wallet connect Prism asks this dev control server (POST /dev/fund) to top the wallet up with test
# xDAI on the anvil fork, and blocks sending while the wallet's own network is not the fork. Honoured only for a loopback
# origin; production builds never set it.
NEXT_PUBLIC_PINE_DEV_FORK_ORIGIN=http://127.0.0.1:$CONTROL_PORT
EOF
chmod 644 "$STATE_DIR/frontend.env"

# ------------------------------------------------------------------------------------------------ indexer + API dev server
start_service() {
  # $1 name, $2 cwd, $3 port that must be free, rest: command
  local name=$1 cwd=$2 port=$3
  shift 3
  port_busy "$port" && die "port $port is in use by a process up.sh did not start (needed by $name)"
  node "$DEV_STACK_DIR/spawn-detached.mjs" "$cwd" "$LOG_DIR/$name.log" "$PID_DIR/$name.pid" -- "$@"
  log "$name: started (pid $(service_pid "$name" || echo '?'), log $LOG_DIR/$name.log)"
}

wait_http() {
  # $1 name, $2 url, $3 seconds
  local name=$1 url=$2 seconds=$3
  for _ in $(seq 1 $((seconds * 2))); do
    [ "$(curl -s -o /dev/null -w '%{http_code}' -m 3 "$url" || true)" = "200" ] && return 0
    service_pid "$name" >/dev/null || die "$name exited (see $LOG_DIR/$name.log)"
    sleep 0.5
  done
  die "$name did not become ready at $url within ${seconds}s (see $LOG_DIR/$name.log)"
}

if [ "$RESTART" = 1 ] || [ -n "$INDEXER_ENV_CHANGED" ] || ! service_pid indexer >/dev/null; then
  stop_service indexer
  start_service indexer "$REPO_ROOT/packages/indexer-native" "$INDEXER_METRICS_PORT" \
    node --env-file="$STATE_DIR/indexer.env" --import tsx src/main.ts
else
  log "indexer: running (pid $(service_pid indexer))"
fi
wait_http indexer "http://127.0.0.1:$INDEXER_METRICS_PORT/readyz" 120

if [ "$RESTART" = 1 ] || [ -n "$API_ENV_CHANGED" ] || ! service_pid api >/dev/null; then
  stop_service api
  for port in "$USER_CONTENT_PORT" "$API_METRICS_PORT" "$CONTROL_PORT"; do
    port_busy "$port" && die "port $port is in use by a process up.sh did not start (needed by the API dev server)"
  done
  start_service api "$REPO_ROOT/packages/api" "$API_PORT" \
    node --env-file="$STATE_DIR/api.env" --import tsx scripts/dev-server.ts
else
  log "api: running (pid $(service_pid api))"
fi
wait_http api "http://127.0.0.1:$API_PORT/healthz" 90
wait_http api "http://127.0.0.1:$CONTROL_PORT/dev/health" 30
wait_http api "http://127.0.0.1:$API_PORT/readyz" 120

cat <<EOF

[dev-stack] READY (development only; local anvil fork, nothing touches a real network)
  API              http://127.0.0.1:$API_PORT   (healthz, readyz, /api/v1/*, /api/openapi.json, /.well-known/pine.json)
  user content     $USER_CONTENT_ORIGIN
  dev control      http://127.0.0.1:$CONTROL_PORT/dev/health   (faucet: POST /dev/fund, see README "Your own wallet on the fork")
  anvil (chain 100) $RPC_PRIMARY   head $(rpc_call eth_blockNumber | jq -r '.result' | xargs printf '%d')
  postgres         127.0.0.1:$PG_PORT/$PG_DB   (container $PG_CONTAINER)
  indexer health   http://127.0.0.1:$INDEXER_METRICS_PORT/readyz
  frontend env     $STATE_DIR/frontend.env
  logs             $LOG_DIR
  Expected web origin: $PUBLIC_ORIGIN (proxy /api/v1/*, /api/openapi.json, /.well-known/pine.json, /healthz, /readyz to :$API_PORT)
EOF
