#!/usr/bin/env node
// Exports the ABIs of the frozen Solidity interfaces (contracts/src/interfaces) to
// packages/shared/src/abi/generated.ts as `as const` arrays for viem.
//   node scripts/export-abis.mjs           write the file (run `forge build` in contracts/ first)
//   node scripts/export-abis.mjs --check   exit 1 when the committed file differs from the compiled interfaces
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "contracts", "out");
const target = path.join(root, "packages", "shared", "src", "abi", "generated.ts");
const interfaces = [
  ["IClaimRegistry", "claimRegistryAbi"],
  ["IEvidenceRegistry", "evidenceRegistryAbi"],
];

let text = "// GENERATED by scripts/export-abis.mjs from contracts/src/interfaces. Do not edit.\n\n";
for (const [name, exportName] of interfaces) {
  const artifact = path.join(out, `${name}.sol`, `${name}.json`);
  if (!existsSync(artifact)) {
    console.error(`Missing ${artifact}; run forge build in contracts/ first.`);
    process.exit(2);
  }
  const abi = JSON.parse(readFileSync(artifact, "utf8")).abi;
  // Stable order: by type then name, so recompilation never reorders the file.
  abi.sort((a, b) => `${a.type}:${a.name ?? ""}`.localeCompare(`${b.type}:${b.name ?? ""}`));
  text += `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== text) {
    console.error("packages/shared/src/abi/generated.ts is out of date with contracts/src/interfaces");
    process.exit(1);
  }
  console.log("ABI export is up to date");
} else {
  writeFileSync(target, text);
  console.log(`Wrote ${path.relative(root, target)}`);
}
