/**
 * JSON Schema (draft 2020-12) for ClaimManifest (manifestVersion "1"), plus a compact schema for
 * AgentClaimBrief. Keep in sync with packages/core/src/types.ts.
 */
import { AGENT_BRIEF_SCHEMA_URL, CLAIM_MANIFEST_SCHEMA_URL } from '../manifest'

const hash32 = { type: 'string', pattern: '^0x[0-9a-fA-F]{64}$' }
const address = { type: 'string', pattern: '^0x[0-9a-fA-F]{40}$' }
const sha40 = { type: 'string', pattern: '^[0-9a-fA-F]{40}$' }
const utc = { type: 'string', format: 'date-time', pattern: 'Z$' }
const decimal = { type: 'string', pattern: '^[0-9]+(\\.[0-9]+)?$' }
const strings = { type: 'array', items: { type: 'string' } }

export const CLAIM_MANIFEST_JSON_SCHEMA: Record<string, unknown> = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: CLAIM_MANIFEST_SCHEMA_URL,
  title: 'Pine claim manifest',
  description:
    'Immutable record of one bounded, policy-versioned claim about an exact GitHub commit. manifestHash = keccak256(UTF-8(RFC 8785 canonical JSON of this document)).',
  type: 'object',
  required: ['$schema', 'manifestVersion', 'claimId', 'createdAt', 'creator', 'source', 'policy', 'claim', 'question', 'disclaimers'],
  additionalProperties: false,
  properties: {
    $schema: { const: CLAIM_MANIFEST_SCHEMA_URL },
    manifestVersion: { const: '1' },
    claimId: { type: 'string', minLength: 1 },
    createdAt: utc,
    creator: address,
    source: { $ref: '#/$defs/SourceRef' },
    policy: {
      type: 'object',
      required: ['id', 'version', 'hash', 'uri'],
      additionalProperties: false,
      properties: {
        id: { type: 'string', pattern: '^[A-Z]+-[0-9]{3}$' },
        version: { type: 'string' },
        hash: hash32,
        uri: { type: 'string' },
      },
    },
    claim: { $ref: '#/$defs/ClaimSpec' },
    question: { $ref: '#/$defs/ClaimQuestion' },
    disclaimers: strings,
  },
  $defs: {
    SourceRef: {
      type: 'object',
      required: ['provider', 'owner', 'repo', 'commit'],
      additionalProperties: false,
      properties: {
        provider: { const: 'github' },
        owner: { type: 'string', minLength: 1 },
        repo: { type: 'string', minLength: 1 },
        repoId: { type: 'integer' },
        pullRequest: {
          type: 'object',
          required: ['number', 'title', 'htmlUrl', 'author', 'state'],
          additionalProperties: false,
          properties: {
            number: { type: 'integer', minimum: 1 },
            title: { type: 'string' },
            htmlUrl: { type: 'string' },
            author: { type: 'string' },
            state: { enum: ['open', 'closed', 'merged'] },
          },
        },
        commit: {
          type: 'object',
          required: ['sha', 'message', 'author', 'committedAt', 'htmlUrl'],
          additionalProperties: false,
          properties: {
            sha: sha40,
            message: { type: 'string' },
            author: { type: 'string' },
            committedAt: { type: 'string' },
            htmlUrl: { type: 'string' },
          },
        },
        baseCommit: {
          type: 'object',
          required: ['sha', 'htmlUrl'],
          additionalProperties: false,
          properties: { sha: sha40, htmlUrl: { type: 'string' } },
        },
        license: { type: ['string', 'null'] },
      },
    },
    EnvironmentPin: {
      type: 'object',
      required: ['runtime', 'config', 'configHash', 'reproductionCommand', 'setupSteps', 'envHash'],
      additionalProperties: false,
      properties: {
        runtime: { type: 'string', minLength: 1 },
        packageManager: { type: 'string' },
        dependencyLock: {
          type: 'object',
          required: ['path', 'hash'],
          additionalProperties: false,
          properties: { path: { type: 'string' }, hash: hash32 },
        },
        config: { type: 'object', additionalProperties: { type: 'string' } },
        configHash: { ...hash32, description: 'keccak256(canonical JSON of config)' },
        containerImage: { type: 'string' },
        externalState: { type: 'string' },
        reproductionCommand: { type: 'string', minLength: 1 },
        setupSteps: strings,
        notes: { type: 'string' },
        envHash: { ...hash32, description: 'keccak256(canonical JSON of this object without envHash)' },
      },
    },
    OracleParams: {
      type: 'object',
      required: ['chainId', 'openingTime', 'timeoutSeconds', 'minBond', 'bondToken', 'arbitrator', 'arbitratorName', 'language', 'category'],
      additionalProperties: false,
      properties: {
        chainId: { type: 'integer' },
        openingTime: utc,
        timeoutSeconds: { type: 'integer', minimum: 3600 },
        minBond: decimal,
        bondToken: { type: 'string' },
        arbitrator: address,
        arbitratorName: { type: 'string' },
        language: { type: 'string' },
        category: { type: 'string' },
      },
    },
    ClaimSpec: {
      type: 'object',
      required: [
        'title',
        'policyId',
        'policyVersion',
        'requirement',
        'violation',
        'scope',
        'parameters',
        'assumptions',
        'exclusions',
        'environment',
        'regressionOnly',
        'evidence',
        'oracle',
      ],
      additionalProperties: false,
      properties: {
        title: { type: 'string', minLength: 1, maxLength: 90 },
        policyId: { type: 'string' },
        policyVersion: { type: 'string' },
        claimClass: { type: 'string' },
        requirement: { type: 'string', minLength: 1, maxLength: 4000 },
        violation: { type: 'string', minLength: 1, maxLength: 500 },
        scope: {
          type: 'object',
          required: ['inScope', 'outOfScope'],
          additionalProperties: false,
          properties: { inScope: strings, outOfScope: strings },
        },
        parameters: {
          type: 'object',
          additionalProperties: { anyOf: [{ type: 'string' }, strings, { type: 'boolean' }] },
        },
        faultModel: { type: 'string' },
        allowedInputs: { type: 'string' },
        assumptions: strings,
        exclusions: strings,
        environment: { $ref: '#/$defs/EnvironmentPin' },
        regressionOnly: { type: 'boolean' },
        evidence: {
          type: 'object',
          required: ['mechanism', 'deadline'],
          additionalProperties: false,
          properties: {
            mechanism: { enum: ['erc1497-arbitrator-proxy', 'commit-reveal'] },
            deadline: utc,
          },
        },
        oracle: { $ref: '#/$defs/OracleParams' },
        specReference: {
          type: 'object',
          required: ['label', 'url'],
          additionalProperties: false,
          properties: { label: { type: 'string' }, url: { type: 'string' }, hash: hash32 },
        },
      },
    },
    ClaimQuestion: {
      type: 'object',
      required: ['text', 'outcomes', 'hash'],
      additionalProperties: false,
      properties: {
        text: { type: 'string', minLength: 1 },
        outcomes: { type: 'array', items: { type: 'string' }, minItems: 2 },
        hash: { ...hash32, description: 'keccak256(UTF-8(text))' },
      },
    },
  },
}

/** Compact JSON Schema for AgentClaimBrief (top-level shape and key fields). */
export const AGENT_CLAIM_BRIEF_JSON_SCHEMA: Record<string, unknown> = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: AGENT_BRIEF_SCHEMA_URL,
  title: 'Pine agent claim brief',
  type: 'object',
  required: [
    'schema',
    'id',
    'number',
    'url',
    'status',
    'question',
    'questionHash',
    'manifest',
    'policy',
    'target',
    'requirement',
    'violation',
    'scope',
    'assumptions',
    'exclusions',
    'environment',
    'reproduction',
    'evidence',
    'disclaimers',
    'updatedAt',
  ],
  properties: {
    schema: { type: 'string' },
    id: { type: 'string' },
    number: { type: 'integer' },
    url: { type: 'string' },
    status: {
      enum: ['draft', 'publishing', 'open', 'awaiting_answer', 'answer_proposed', 'disputed', 'arbitration', 'resolved', 'settled', 'failed'],
    },
    outcome: { enum: ['yes', 'no', 'invalid'] },
    question: { type: 'string' },
    questionHash: hash32,
    manifest: {
      type: 'object',
      required: ['uri', 'hash', 'jsonUrl'],
      properties: { uri: { type: 'string' }, hash: hash32, jsonUrl: { type: 'string' } },
    },
    policy: {
      type: 'object',
      required: ['id', 'version', 'hash', 'uri', 'url', 'title'],
      properties: {
        id: { type: 'string' },
        version: { type: 'string' },
        hash: hash32,
        uri: { type: 'string' },
        url: { type: 'string' },
        title: { type: 'string' },
      },
    },
    target: {
      type: 'object',
      required: ['repository', 'commit', 'commitUrl'],
      properties: {
        repository: { type: 'string' },
        commit: { type: 'string' },
        commitUrl: { type: 'string' },
        baseCommit: { type: 'string' },
        pullRequest: { type: 'string' },
      },
    },
    requirement: { type: 'string' },
    violation: { type: 'string' },
    scope: { type: 'object', properties: { inScope: strings, outOfScope: strings } },
    faultModel: { type: 'string' },
    assumptions: strings,
    exclusions: strings,
    environment: { $ref: `${CLAIM_MANIFEST_SCHEMA_URL}#/$defs/EnvironmentPin` },
    reproduction: {
      type: 'object',
      required: ['command', 'setupSteps'],
      properties: { command: { type: 'string' }, setupSteps: strings },
    },
    evidence: {
      type: 'object',
      required: ['mechanism', 'deadline', 'deadlineTs', 'requirements', 'submitUrl'],
      properties: {
        mechanism: { type: 'object' },
        deadline: utc,
        deadlineTs: { type: 'integer' },
        requirements: strings,
        submitUrl: { type: 'string' },
      },
    },
    market: { type: 'object' },
    oracle: { type: 'object' },
    disclaimers: strings,
    updatedAt: { type: 'string' },
  },
}
